version: '3.9'

services:
  konkurs:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: konkurs
    restart: always
    volumes:
      - /root/MyPortfolio/DB:/app/DB
      - /root/MyPortfolio/Files:/app/Files
    ports:
      - "5034:5034"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__SQLiteConnection=Data Source=/app/DB/KonkursBot.db
      - BotConfiguration__BotToken=5255513447:AAGe6QnkefU1VT9jNH8yj4S02OlUWBN0Hsk
      - BotConfiguration__HostAddress=https://e35a-188-113-248-157.ngrok-free.app
      - BotConfiguration__SecretKey=qwertyuiopasdfghjkl
      - BotConfiguration__Route=/api/bot
    networks:
      - konkurs_network

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: konkurs_nginx
    ports:
      - "8443:8443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
      - konkurs_network

networks:
  konkurs_network:
    driver: bridge